# Generated by Django 6.0.7 on 2026-07-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the disease')),
                ('causes', models.TextField(help_text='Primary causes of the disease')),
                ('precautions', models.TextField(help_text='Comma-separated precautions or guidelines')),
                ('specialist', models.CharField(help_text='Specialist medical field suggested', max_length=255)),
            ],
        ),
    ]
