# Generated by Django 6.0.7 on 2026-07-18 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Comma-separated symptoms selected')),
                ('predicted_disease', models.CharField(help_text='Predicted disease name', max_length=255)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Percentage confidence score')),
                ('medicines', models.TextField(blank=True, help_text='Comma-separated list of recommended medications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
