# Generated by Django 6.0.7 on 2026-07-18 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.TextField(help_text='Standard dosage information')),
                ('side_effects', models.TextField(help_text='Common side effects')),
                ('warnings', models.TextField(help_text='Contraindications and emergency warnings')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='predictor.disease')),
            ],
        ),
    ]
